name: Deploy to production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    environment:
      name: contabo
    steps:
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          source : "deploy.tar"
          overwrite: true
          target: '/home/swordsouler/StreamBlades-TwitchBot/'
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          script: cd StreamBlades-TwitchBot && sh docker-run.sh
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
